### ISSUE TITLE
Milestone: Decompile ASM to C

### ISSUE THREAD

**Issue by PikalaxALT** [pret/pokefirered#196]
If you wish to contribute to this milestone, please [join the Discord](https://discord.gg/d5dubZ3) and claim a file from this list in \#pokefirered.

- [x] asm/text_printer.s
- [x] asm/battle_bg.s
- [x] asm/battle_interface.s
- [x] asm/smokescreen.s
- [x] asm/overworld.s
- [x] asm/field_camera.s
- [x] asm/field_player_avatar.s
- [x] asm/event_object_movement.s
- [x] ~~asm/field_ground_effect.s~~ folded into event_object_movement
- [x] asm/event_object_80688E4.s *TODO: fold into event_object_movement*
- [x] asm/field_message_box.s
- [x] asm/field_control_avatar.s
- [x] asm/field_tasks.s
- [x] asm/field_weather.s
- [x] asm/field_weather_effects.s
- [x] asm/field_screen_effect.s
- [x] asm/cable_club.s
- [x] asm/trainer_see.s
- [x] asm/field_effect.s
- [x] asm/pokemon_storage_system.s
- [x] asm/script_movement.s
- [x] asm/fldeff_cut.s
- [x] asm/naming_screen.s
- [x] asm/script_pokemon_util_80A0058.s
- [x] asm/pc_screen_effect.s
- [x] asm/water.s
- [x] asm/bike.s
- [x] asm/script_pokemon_util_80BF8FC.s
- [x] asm/region_map.s
- [x] asm/fldeff_flash.s
- [x] asm/post_battle_event_funcs.s
- [x] asm/field_effect_helpers.s
- [x] asm/save_failed_screen.s
- [x] asm/clear_save_data_screen.s
- [x] asm/box_party_pokemon_dropdown.s
- [x] asm/link_rfu_2.s  --> src/link_rfu_2.c, src/link_rfu_3.c
- [x] asm/easy_chat_2.s --> src/easy_chat_2.c, src/easy_chat_3.c
- [x] asm/link_rfu.s
- [x] asm/pokedex_screen.s
- [x] asm/item_menu.s
- [x] ~~asm/link_rfu_3.s~~ asm/union_room.s
- [x] asm/pokemon_special_anim.s
- [x] asm/union_room_chat.s
- [x] asm/pokemon_summary_screen.s
- [x] asm/pokemon_jump.s
- [x] asm/pokemon_jump_2.s --> src/pokemon_jump_[2-6].c
- [x] asm/berry_crush.s
- [x] asm/berry_crush_2.s
- [x] asm/berry_crush_3.s
- [x] asm/dodrio_berry_picking.s
- [x] asm/dodrio_berry_picking_2.s
- [x] asm/librfu_stwi.s
- [x] asm/librfu.s

**Comment by Delta456** [comment]
This should be updated.

**Comment by PikalaxALT** [comment]
Progress as of 22 Feb 2020: 
```
1472552 total bytes of code
1164020 bytes of code in src (79.0478%)
308532 bytes of code in asm (20.9522%)

54109 total symbols
40642 symbols documented (75.1113%)
3424 symbols partially documented (6.3280%)
10043 symbols undocumented (18.5607%)

5163367 total bytes of data
1210057 bytes of data in src (23.4354%)
3953310 bytes of data in data (76.5646%)
```

**Comment by coltongit** [comment]
Quite a bit of progress has been made towards this milestone even since the last post. We're moving quick

**Comment by ketsuban** [comment]
End-of-March update:

```
pokefirered progress:
1472552 total bytes of code
1427996 bytes of code in src (96.9742%)
44556 bytes of code in asm (3.0258%)

54037 total symbols
48420 symbols documented (89.6053%)
1259 symbols partially documented (2.3299%)
4358 symbols undocumented (8.0648%)

6993950 total bytes of data
3446925 bytes of data in src (49.2844%)
3547025 bytes of data in data (50.7156%)
```

**Comment by hjk321** [comment]
We reached 100% decompilation a few days ago. Should this be closed?

**Comment by GriffinRichards** [comment]
Yes
